import { Employee } from "../_model/app.model";

export const bankData = [
    {
        "id": "3cf214f7-zdfg-562e-a0f9-5eljzz474cea",
        "position": 1,
        "username": "benni",
        "firstName": "benni",
        "lastName": "simarmata",
        "email": "benni@example.com",
        "birthDate": "Sun Jun 20 1999",
        "basicSalary": 100000,
        "status": "On Leave",
        "group": "Software Development",
        "description": "Setiap hari adalah awal yang baru. Tarik napas dalam, dan mulai lagi."
    },
    {
        "id": "3cf214f7-95df-kk89-a0f9-5a4xzz474cea",
        "position": 2,
        "username": "admin",
        "firstName": "admin",
        "lastName": "management",
        "email": "admin@example.com",
        "birthDate": "Sun Jun 20 2024",
        "basicSalary": 60000,
        "status": "Intern",
        "group": "HR",
        "description": "Langkah kecil setiap hari akan membawa hasil besar."
    },
    {
        "id": "d687e364-c6b4-493e-a26e-27b5da1eb10c",
        "position": 3,
        "username": "john",
        "firstName": "John",
        "lastName": "Michael",
        "email": "johnmichael@example.com",
        "birthDate": "Thu Feb 24 1994",
        "basicSalary": 35730,
        "status": "Part-Time",
        "group": "Sales",
        "description": "Kepercayaan diri adalah awal dari kesuksesan"
    },
    {
        "id": "0a6deffc-eb20-4e32-bcf5-c7009ee8b01c",
        "position": 4,
        "username": "david",
        "firstName": "David",
        "lastName": "Robert",
        "email": "davidrobert@example.com",
        "birthDate": "Mon Apr 18 1994",
        "basicSalary": 66947,
        "status": "Available for Hire",
        "group": "Software Development",
        "description": "Jangan hanya melihat hasil, tapi juga proses yang telah dilewati"
    },
    {
        "id": "815b2513-b1cf-4929-a699-19613231d422",
        "position": 5,
        "username": "james",
        "firstName": "James",
        "lastName": "Anthony",
        "email": "jamesanthony@example.com",
        "birthDate": "Sat Dec 27 1986",
        "basicSalary": 101384,
        "status": "Remote",
        "group": "HR",
        "description": "Jangan hanya bekerja untuk uang, tapi juga untuk kepuasan diri"
    },
    {
        "id": "64fcaaa2-d569-42f5-9fb4-c2d26beab2ff",
        "position": 6,
        "username": "william",
        "firstName": "William",
        "lastName": "Thomas",
        "email": "williamthomas@example.com",
        "birthDate": "Thu Nov 21 1996",
        "basicSalary": 40923,
        "status": "Resigned",
        "group": "Customer Service",
        "description": "Mimpi besar membutuhkan usaha besar"
    },
    {
        "id": "9c2347b7-9104-4656-8f78-505afe0b7b5d",
        "position": 7,
        "username": "richard",
        "firstName": "Richard",
        "lastName": "Daniel",
        "email": "richarddaniel@example.com",
        "birthDate": "Sun Aug 14 1994",
        "basicSalary": 102181,
        "status": "Suspended",
        "group": "HR",
        "description": "Teruslah berkembang dan beradaptasi dengan perubahan"
    },
    {
        "id": "caf72bd0-5eec-409c-aad5-dc23ddb12675",
        "position": 8,
        "username": "matthew",
        "firstName": "Matthew",
        "lastName": "Steven",
        "email": "matthewsteven@example.com",
        "birthDate": "Wed Jan 08 1992",
        "basicSalary": 110901,
        "status": "Dismissed",
        "group": "Network Engineering",
        "description": "Dunia terus bergerak, jangan sampai tertinggal"
    },
    {
        "id": "7fb91d52-8fa4-4e06-9cff-879da18e902c",
        "position": 9,
        "username": "andrew",
        "firstName": "Andrew",
        "lastName": "Kenneth",
        "email": "andrewkenneth@example.com",
        "birthDate": "Fri Oct 04 2002",
        "basicSalary": 39391,
        "status": "Resigned",
        "group": "HR",
        "description": "Coding adalah seni yang terus berkembang"
    },
    {
        "id": "f5014b21-0ede-4c18-bfb8-2ecb5c637fb0",
        "position": 10,
        "username": "joshua",
        "firstName": "Joshua",
        "lastName": "Kevin",
        "email": "joshuakevin@example.com",
        "birthDate": "Sat May 03 1986",
        "basicSalary": 43540,
        "status": "Remote",
        "group": "Finance",
        "description": "Tidak ada batasan untuk belajar dan berkembang"
    },
    {
        "id": "61f4601f-ce44-41d6-abf0-52e5ff35c259",
        "position": 11,
        "username": "charles",
        "firstName": "Charles",
        "lastName": "Patrick",
        "email": "charlespatrick@example.com",
        "birthDate": "Sat Dec 05 1998",
        "basicSalary": 95122,
        "status": "Terminated",
        "group": "Customer Service",
        "description": "Jadilah versi terbaik dari dirimu sendiri"
    },
    {
        "id": "b8c3bdbe-8fe4-47ad-8e95-8152e6f23c7c",
        "position": 12,
        "username": "joseph",
        "firstName": "Joseph",
        "lastName": "Raymond",
        "email": "josephraymond@example.com",
        "birthDate": "Mon Feb 17 1986",
        "basicSalary": 92743,
        "status": "Available for Hire",
        "group": "Public Relations",
        "description": "Komunikasi yang baik membangun hubungan yang kuat"
    },
    {
        "id": "c4643d6c-5c8d-4379-9346-2edc14efbaa5",
        "position": 13,
        "username": "jessica",
        "firstName": "Jessica",
        "lastName": "Anne",
        "email": "jessicaanne@example.com",
        "birthDate": "Mon Apr 03 1989",
        "basicSalary": 39810,
        "status": "Inactive",
        "group": "Sales",
        "description": "Jangan hanya bekerja keras, tapi juga bekerja cerdas"
    },
    {
        "id": "c344fd47-568b-477a-9fa7-84dd53908a56",
        "position": 14,
        "username": "emily",
        "firstName": "Emily",
        "lastName": "Sophia",
        "email": "emilysophia@example.com",
        "birthDate": "Sat Jul 19 1986",
        "basicSalary": 100342,
        "status": "Layoff",
        "group": "DevOps",
        "description": "Keahlian tidak datang secara instan, teruslah berlatih"
    },
    {
        "id": "948718c3-8294-4d72-8087-16d6edc0be8a",
        "position": 15,
        "username": "sarah",
        "firstName": "Sarah",
        "lastName": "Elizabeth",
        "email": "sarahelizabeth@example.com",
        "birthDate": "Wed Dec 15 1993",
        "basicSalary": 98465,
        "status": "Medical Leave",
        "group": "UI/UX Design",
        "description": "Komunikasi yang baik membangun hubungan yang kuat"
    },
    {
        "id": "813d17ba-9245-486e-95d2-6ed7c04541bb",
        "position": 16,
        "username": "amanda",
        "firstName": "Amanda",
        "lastName": "Nicole",
        "email": "amandanicole@example.com",
        "birthDate": "Tue Dec 17 1996",
        "basicSalary": 101404,
        "status": "Retired",
        "group": "UI/UX Design",
        "description": "Berpikirlah positif, karena pikiran adalah awal dari segalanya"
    },
    {
        "id": "f196f47e-7bfe-4451-8942-7cfe6eb4b969",
        "position": 17,
        "username": "megan",
        "firstName": "Megan",
        "lastName": "Olivia",
        "email": "meganolivia@example.com",
        "birthDate": "Tue Apr 09 1996",
        "basicSalary": 49950,
        "status": "Resigned",
        "group": "Customer Service",
        "description": "Kepercayaan diri adalah awal dari kesuksesan"
    },
    {
        "id": "e91312eb-185a-45af-912e-711e47b704d3",
        "position": 18,
        "username": "lauren",
        "firstName": "Lauren",
        "lastName": "Grace",
        "email": "laurengrace@example.com",
        "birthDate": "Mon Apr 11 1994",
        "basicSalary": 116015,
        "status": "Resigned",
        "group": "Finance",
        "description": "Jangan takut gagal, karena setiap kegagalan adalah pengalaman"
    },
    {
        "id": "1ce37f64-413c-4c85-8312-68b9f9353288",
        "position": 19,
        "username": "hannah",
        "firstName": "Hannah",
        "lastName": "Marie",
        "email": "hannahmarie@example.com",
        "birthDate": "Wed Dec 12 2001",
        "basicSalary": 74566,
        "status": "Training",
        "group": "HR",
        "description": "Setiap tantangan adalah kesempatan untuk tumbuh lebih kuat"
    },
    {
        "id": "207abbbc-a0ee-4eca-ad7c-9df33c6e2900",
        "position": 20,
        "username": "rebecca",
        "firstName": "Rebecca",
        "lastName": "Charlotte",
        "email": "rebeccacharlotte@example.com",
        "birthDate": "Wed Nov 28 2001",
        "basicSalary": 73549,
        "status": "Intern",
        "group": "Public Relations",
        "description": "Saling mendukung akan membawa tim ke level lebih tinggi"
    },
    {
        "id": "2b54b671-1fad-43d3-8b5b-393e499cdc05",
        "position": 21,
        "username": "isabella",
        "firstName": "Isabella",
        "lastName": "Rose",
        "email": "isabellarose@example.com",
        "birthDate": "Tue Nov 17 1992",
        "basicSalary": 108105,
        "status": "Consultant",
        "group": "UI/UX Design",
        "description": "Teruslah berkembang dan beradaptasi dengan perubahan"
    },
    {
        "id": "902e87d8-358c-4dea-b55b-ffcdea1ec2b0",
        "position": 22,
        "username": "madison",
        "firstName": "Madison",
        "lastName": "Claire",
        "email": "madisonclaire@example.com",
        "birthDate": "Tue Apr 24 2001",
        "basicSalary": 110072,
        "status": "Part-Time",
        "group": "Finance",
        "description": "Jangan biarkan kegagalan menghentikan langkahmu"
    },
    {
        "id": "546a304c-80ea-494d-a87f-4e1dea09b87c",
        "position": 23,
        "username": "budi",
        "firstName": "Budi",
        "lastName": "Santoso",
        "email": "budisantoso@example.com",
        "birthDate": "Wed Mar 26 1986",
        "basicSalary": 61053,
        "status": "Intern",
        "group": "HR",
        "description": "Sabar dalam proses, karena hasil akan datang pada waktunya"
    },
    {
        "id": "3cb4e997-be42-407c-bfba-c2c54e24eece",
        "position": 24,
        "username": "rizky",
        "firstName": "Rizky",
        "lastName": "Pratama",
        "email": "rizkypratama@example.com",
        "birthDate": "Wed Dec 11 1991",
        "basicSalary": 100326,
        "status": "Temporary",
        "group": "DevOps",
        "description": "Kembangkan diri setiap hari, walau hanya sedikit"
    },
    {
        "id": "498354dd-7bab-447a-bed2-3952a90ab59a",
        "position": 25,
        "username": "bayu",
        "firstName": "Bayu",
        "lastName": "Saputra",
        "email": "bayusaputra@example.com",
        "birthDate": "Sat Aug 19 1995",
        "basicSalary": 43985,
        "status": "Maternity Leave",
        "group": "Software Development",
        "description": "Kolaborasi adalah kunci keberhasilan"
    },
    {
        "id": "775582de-80a2-4896-84f0-1138fb12dcfb",
        "position": 26,
        "username": "andi",
        "firstName": "Andi",
        "lastName": "Wijaya",
        "email": "andiwijaya@example.com",
        "birthDate": "Thu Jan 21 1988",
        "basicSalary": 101248,
        "status": "Sabbatical",
        "group": "Network Engineering",
        "description": "Waktu adalah aset yang paling berharga, gunakan dengan bijak"
    },
    {
        "id": "624b9fff-a15b-48d2-b2a5-fa22f7086c63",
        "position": 27,
        "username": "dedi",
        "firstName": "Dedi",
        "lastName": "Kurniawan",
        "email": "dedikurniawan@example.com",
        "birthDate": "Mon Aug 17 1992",
        "basicSalary": 112610,
        "status": "Suspended",
        "group": "Customer Service",
        "description": "Teruslah berkembang dan beradaptasi dengan perubahan"
    },
    {
        "id": "4af2ba21-66c2-4131-acc0-e961ce3ad1ca",
        "position": 28,
        "username": "hendra",
        "firstName": "Hendra",
        "lastName": "Setiawan",
        "email": "hendrasetiawan@example.com",
        "birthDate": "Wed Nov 10 2004",
        "basicSalary": 78754,
        "status": "Probation",
        "group": "HR",
        "description": "Jangan lupa istirahat dan tetap sehat"
    },
    {
        "id": "e6e0c67a-0db4-43fa-ad2a-59c71fe3dba3",
        "position": 29,
        "username": "joko",
        "firstName": "Joko",
        "lastName": "Susanto",
        "email": "jokosusanto@example.com",
        "birthDate": "Sun Nov 25 2001",
        "basicSalary": 101587,
        "status": "Layoff",
        "group": "Finance",
        "description": "Tetap rendah hati dalam setiap pencapaian"
    },
    {
        "id": "bc3a9960-1ff7-471c-9598-948a72a7c59a",
        "position": 30,
        "username": "eko",
        "firstName": "Eko",
        "lastName": "Supriyanto",
        "email": "ekosupriyanto@example.com",
        "birthDate": "Thu Mar 17 1994",
        "basicSalary": 97782,
        "status": "Resigned",
        "group": "Sales",
        "description": "Kolaborasi adalah kunci keberhasilan"
    },
    {
        "id": "e1a53d4a-68bf-41fb-815b-16bd5b24110e",
        "position": 31,
        "username": "yanto",
        "firstName": "Yanto",
        "lastName": "Rahardjo",
        "email": "yantorahardjo@example.com",
        "birthDate": "Wed Aug 10 1988",
        "basicSalary": 97170,
        "status": "Under Review",
        "group": "Public Relations",
        "description": "Kolaborasi adalah kunci keberhasilan"
    },
    {
        "id": "32ea4440-20c7-4513-9184-bb261f3d4836",
        "position": 32,
        "username": "putri",
        "firstName": "Putri",
        "lastName": "Maharani",
        "email": "putrimaharani@example.com",
        "birthDate": "Mon Jun 24 2002",
        "basicSalary": 80951,
        "status": "Under Review",
        "group": "Sales",
        "description": "Jangan takut gagal, karena setiap kegagalan adalah pengalaman"
    },
    {
        "id": "377c6194-48a0-45dd-8cd3-ccbea8fc9e29",
        "position": 33,
        "username": "siti",
        "firstName": "Siti",
        "lastName": "Nurhaliza",
        "email": "sitinurhaliza@example.com",
        "birthDate": "Sun May 25 2003",
        "basicSalary": 35024,
        "status": "Transferred",
        "group": "Software Development",
        "description": "Tetap rendah hati dalam setiap pencapaian"
    },
    {
        "id": "bc22e85c-5c88-4314-8cc7-58d5a249960f",
        "position": 34,
        "username": "dewi",
        "firstName": "Dewi",
        "lastName": "Lestari",
        "email": "dewilestari@example.com",
        "birthDate": "Sat Dec 28 1985",
        "basicSalary": 54186,
        "status": "Temporary",
        "group": "HR",
        "description": "Kreativitas tidak memiliki batas"
    },
    {
        "id": "3c07fcfa-3985-4511-934d-33feaeacf388",
        "position": 35,
        "username": "ayu",
        "firstName": "Ayu",
        "lastName": "Fitriani",
        "email": "ayufitriani@example.com",
        "birthDate": "Wed Dec 12 1990",
        "basicSalary": 85779,
        "status": "Layoff",
        "group": "UI/UX Design",
        "description": "Dunia terus bergerak, jangan sampai tertinggal"
    },
    {
        "id": "293d6e88-9d06-48ff-aed4-ddc29f0e8e1d",
        "position": 36,
        "username": "ratna",
        "firstName": "Ratna",
        "lastName": "Sari",
        "email": "ratnasari@example.com",
        "birthDate": "Wed Jun 20 2001",
        "basicSalary": 35089,
        "status": "Intern",
        "group": "UI/UX Design",
        "description": "Jangan menunda pekerjaan, karena waktu tidak bisa diulang"
    },
    {
        "id": "2e62ff33-b506-435c-9dac-5ddbf8d1ac86",
        "position": 37,
        "username": "sri",
        "firstName": "Sri",
        "lastName": "Wahyuni",
        "email": "sriwahyuni@example.com",
        "birthDate": "Thu Dec 23 1993",
        "basicSalary": 97547,
        "status": "Intern",
        "group": "DevOps",
        "description": "Tantangan yang sulit akan membuatmu lebih kuat"
    },
    {
        "id": "fdf8799f-57c4-4c91-8b57-e235952aa7cb",
        "position": 38,
        "username": "teguh",
        "firstName": "Teguh",
        "lastName": "Budi",
        "email": "teguhbudi@example.com",
        "birthDate": "Thu Oct 18 2001",
        "basicSalary": 80403,
        "status": "Intern",
        "group": "DevOps",
        "description": "Jangan takut untuk memulai sesuatu yang baru"
    },
    {
        "id": "9265ba5f-5d5a-4906-aed0-b53d2794bc2c",
        "position": 39,
        "username": "rina",
        "firstName": "Rina",
        "lastName": "Puspita",
        "email": "rinapuspita@example.com",
        "birthDate": "Fri Oct 05 2001",
        "basicSalary": 36192,
        "status": "Inactive",
        "group": "Finance",
        "description": "Pikiran positif membawa kehidupan yang lebih baik"
    },
    {
        "id": "482fa60b-eb0a-40dd-bb9b-c6dc82157804",
        "position": 40,
        "username": "rizal",
        "firstName": "Rizal",
        "lastName": "Fahmi",
        "email": "rizalfahmi@example.com",
        "birthDate": "Mon Feb 01 1999",
        "basicSalary": 88005,
        "status": "Freelancer",
        "group": "DevOps",
        "description": "Kualitas lebih penting daripada kuantitas dalam setiap pekerjaan"
    },
    {
        "id": "03a3f3c8-0a60-4fff-b483-b268078cc502",
        "position": 41,
        "username": "hery",
        "firstName": "Hery",
        "lastName": "Prasetyo",
        "email": "heryprasetyo@example.com",
        "birthDate": "Fri Apr 17 1987",
        "basicSalary": 49519,
        "status": "Resigned",
        "group": "Network Engineering",
        "description": "Pekerjaan yang dilakukan dengan hati akan membuahkan hasil"
    },
    {
        "id": "bbb1755d-188c-4feb-828f-37ec5e4b63c3",
        "position": 42,
        "username": "dian",
        "firstName": "Dian",
        "lastName": "Wulandari",
        "email": "dianwulandari@example.com",
        "birthDate": "Thu Aug 27 1998",
        "basicSalary": 85610,
        "status": "Retired",
        "group": "Network Engineering",
        "description": "Mimpi besar hanya bisa diwujudkan dengan aksi nyata"
    },
    {
        "id": "3ea5663e-a743-42fb-ab7a-c6f6108cc96f",
        "position": 43,
        "username": "lucas",
        "firstName": "Lucas",
        "lastName": "Gabriel",
        "email": "lucasgabriel@example.com",
        "birthDate": "Fri Feb 07 1986",
        "basicSalary": 83398,
        "status": "Temporary",
        "group": "HR",
        "description": "Ketika ragu, ingatlah alasanmu memulai"
    },
    {
        "id": "4d400387-31e0-45bc-88a9-f9fde3b9826f",
        "position": 44,
        "username": "alexander",
        "firstName": "Alexander",
        "lastName": "Sebastian",
        "email": "alexandersebastian@example.com",
        "birthDate": "Fri Mar 15 1991",
        "basicSalary": 37998,
        "status": "Training",
        "group": "Customer Service",
        "description": "Pekerjaan yang dilakukan dengan hati akan membuahkan hasil"
    },
    {
        "id": "b46da4ca-e5fa-44e8-9080-1681b3e38aa1",
        "position": 45,
        "username": "benjamin",
        "firstName": "Benjamin",
        "lastName": "Theodore",
        "email": "benjamintheodore@example.com",
        "birthDate": "Thu Apr 22 2004",
        "basicSalary": 73881,
        "status": "Training",
        "group": "Public Relations",
        "description": "Pikiran positif membawa kehidupan yang lebih baik"
    },
    {
        "id": "0eafea9f-7a64-473c-aec4-b14366d457b5",
        "position": 46,
        "username": "christopher",
        "firstName": "Christopher",
        "lastName": "Vincent",
        "email": "christophervincent@example.com",
        "birthDate": "Mon Apr 23 1990",
        "basicSalary": 31955,
        "status": "Terminated",
        "group": "Customer Service",
        "description": "Mimpi besar membutuhkan usaha besar"
    },
    {
        "id": "584a315f-11d8-4267-9f55-44465ab35276",
        "position": 47,
        "username": "dominic",
        "firstName": "Dominic",
        "lastName": "Ethan",
        "email": "dominicethan@example.com",
        "birthDate": "Mon Feb 21 1994",
        "basicSalary": 109109,
        "status": "Resigned",
        "group": "DevOps",
        "description": "Setiap hari adalah kesempatan untuk belajar"
    },
    {
        "id": "2a2fcb2e-e749-4335-abd0-5896932bef8b",
        "position": 48,
        "username": "emma",
        "firstName": "Emma",
        "lastName": "Charlotte",
        "email": "emmacharlotte@example.com",
        "birthDate": "Sat Feb 04 1989",
        "basicSalary": 94855,
        "status": "Active",
        "group": "UI/UX Design",
        "description": "Kesuksesan tidak diukur dari uang, tapi dari dampak yang diberikan"
    },
    {
        "id": "65426f2a-a680-4ba7-a7be-d51bea6e1b94",
        "position": 49,
        "username": "lily",
        "firstName": "Lily",
        "lastName": "Scarlett",
        "email": "lilyscarlett@example.com",
        "birthDate": "Tue Oct 11 1988",
        "basicSalary": 63655,
        "status": "Training",
        "group": "Sales",
        "description": "Setiap tantangan adalah kesempatan untuk tumbuh lebih kuat"
    },
    {
        "id": "c5c5ee86-9b63-4602-ab0b-7c02c61ebb69",
        "position": 50,
        "username": "eleanor",
        "firstName": "Eleanor",
        "lastName": "Hazel",
        "email": "eleanorhazel@example.com",
        "birthDate": "Tue Jan 20 1987",
        "basicSalary": 79830,
        "status": "Transferred",
        "group": "Customer Service",
        "description": "Teruslah berjuang meski jalan terasa berat"
    },
    {
        "id": "6a88684b-c5ef-44e7-8d51-5a40918d7178",
        "position": 51,
        "username": "victoria",
        "firstName": "Victoria",
        "lastName": "Stella",
        "email": "victoriastella@example.com",
        "birthDate": "Tue May 13 2003",
        "basicSalary": 41845,
        "status": "Terminated",
        "group": "Finance",
        "description": "Jangan takut gagal, karena setiap kegagalan adalah pengalaman"
    },
    {
        "id": "0714c3aa-3fe6-4f3c-9202-6a237a8d9e2d",
        "position": 52,
        "username": "amelia",
        "firstName": "Amelia",
        "lastName": "Penelope",
        "email": "ameliapenelope@example.com",
        "birthDate": "Thu Sep 02 1999",
        "basicSalary": 102932,
        "status": "Consultant",
        "group": "HR",
        "description": "Ketika ragu, ingatlah alasanmu memulai"
    },
    {
        "id": "f2c86cc1-9036-4fb1-9ea8-3d899f523289",
        "position": 53,
        "username": "julian",
        "firstName": "Julian",
        "lastName": "Adrian",
        "email": "julianadrian@example.com",
        "birthDate": "Fri Jun 06 1986",
        "basicSalary": 103831,
        "status": "Intern",
        "group": "Finance",
        "description": "Jangan hanya bekerja keras, tapi juga nikmati prosesnya"
    },
    {
        "id": "4a7856d2-18b2-4543-9c56-637788eddfcc",
        "position": 54,
        "username": "felix",
        "firstName": "Felix",
        "lastName": "Oscar",
        "email": "felixoscar@example.com",
        "birthDate": "Wed Apr 05 1989",
        "basicSalary": 119818,
        "status": "Inactive",
        "group": "Finance",
        "description": "Tetap semangat meskipun tantangan terus berdatangan"
    },
    {
        "id": "168a1898-7df5-440d-a391-d2de456116dc",
        "position": 55,
        "username": "oliver",
        "firstName": "Oliver",
        "lastName": "Tristan",
        "email": "olivertristan@example.com",
        "birthDate": "Sun Oct 25 1998",
        "basicSalary": 93550,
        "status": "Contract Ended",
        "group": "Public Relations",
        "description": "Dunia terus bergerak, jangan sampai tertinggal"
    },
    {
        "id": "e3302914-fbcd-45f5-9f7c-51c01bcced71",
        "position": 56,
        "username": "maximilian",
        "firstName": "Maximilian",
        "lastName": "Hugo",
        "email": "maximilianhugo@example.com",
        "birthDate": "Thu Feb 05 1998",
        "basicSalary": 62796,
        "status": "Dismissed",
        "group": "Finance",
        "description": "Tidak ada yang mustahil jika kamu berusaha dengan sungguh-sungguh"
    },
    {
        "id": "883a5cd1-a083-4610-be0e-789de9d70f22",
        "position": 57,
        "username": "stefan",
        "firstName": "Stefan",
        "lastName": "Leonard",
        "email": "stefanleonard@example.com",
        "birthDate": "Sat May 11 2002",
        "basicSalary": 59721,
        "status": "Medical Leave",
        "group": "Technical Support",
        "description": "Jangan takut gagal, karena setiap kegagalan membawa pelajaran"
    },
    {
        "id": "e0591c84-3caf-4788-a43c-6ec598ee9889",
        "position": 58,
        "username": "hiroshi",
        "firstName": "Hiroshi",
        "lastName": "Takashi",
        "email": "hiroshitakashi@example.com",
        "birthDate": "Tue Jul 02 1985",
        "basicSalary": 112601,
        "status": "Terminated",
        "group": "Sales",
        "description": "Kejujuran adalah fondasi dari kepercayaan"
    },
    {
        "id": "fa18c0da-12d3-4def-acde-8011d4c50730",
        "position": 59,
        "username": "kenji",
        "firstName": "Kenji",
        "lastName": "Haruto",
        "email": "kenjiharuto@example.com",
        "birthDate": "Fri Oct 19 2001",
        "basicSalary": 112917,
        "status": "Under Review",
        "group": "DevOps",
        "description": "Dunia terus bergerak, jangan sampai tertinggal"
    },
    {
        "id": "6c404e2a-99fa-4516-b262-342cacfe176e",
        "position": 60,
        "username": "taro",
        "firstName": "Taro",
        "lastName": "Akira",
        "email": "taroakira@example.com",
        "birthDate": "Fri Oct 04 1991",
        "basicSalary": 68334,
        "status": "Under Review",
        "group": "Customer Service",
        "description": "Pikiran positif membawa kehidupan yang lebih baik"
    },
    {
        "id": "55a33e42-9994-49d6-917e-42cdf42b1daa",
        "position": 61,
        "username": "ren",
        "firstName": "Ren",
        "lastName": "Satoshi",
        "email": "rensatoshi@example.com",
        "birthDate": "Thu Apr 17 2003",
        "basicSalary": 53986,
        "status": "Training",
        "group": "Finance",
        "description": "Kepercayaan dibangun dari konsistensi dan integritas"
    },
    {
        "id": "a880d646-9cb2-440f-abf4-1291e9117920",
        "position": 62,
        "username": "daiki",
        "firstName": "Daiki",
        "lastName": "Yamamoto",
        "email": "daikiyamamoto@example.com",
        "birthDate": "Sat Apr 03 2004",
        "basicSalary": 63653,
        "status": "Suspended",
        "group": "Sales",
        "description": "Inovasi adalah jalan menuju kemajuan"
    },
    {
        "id": "784120bd-dac7-4f0e-a9be-30a2dbda8b1d",
        "position": 63,
        "username": "mei",
        "firstName": "Mei",
        "lastName": "Sakura",
        "email": "meisakura@example.com",
        "birthDate": "Fri Apr 20 2001",
        "basicSalary": 94705,
        "status": "Active",
        "group": "HR",
        "description": "Belajar dari orang lain adalah cara terbaik untuk berkembang"
    },
    {
        "id": "0124e152-c7e6-4d44-96dc-7497a5c4a37d",
        "position": 64,
        "username": "yuki",
        "firstName": "Yuki",
        "lastName": "Rina",
        "email": "yukirina@example.com",
        "birthDate": "Mon Nov 23 1987",
        "basicSalary": 119343,
        "status": "Available for Hire",
        "group": "Customer Service",
        "description": "Jangan takut mencoba hal baru"
    },
    {
        "id": "e2f24c42-2e05-4955-81f0-ec790a4c0a1a",
        "position": 65,
        "username": "hana",
        "firstName": "Hana",
        "lastName": "Aiko",
        "email": "hanaaiko@example.com",
        "birthDate": "Sat Sep 02 1989",
        "basicSalary": 33350,
        "status": "Resigned",
        "group": "Customer Service",
        "description": "Jangan takut gagal, karena setiap kegagalan adalah pengalaman"
    },
    {
        "id": "04609c71-0497-42fe-a2f5-601ffc76cc3b",
        "position": 66,
        "username": "kaori",
        "firstName": "Kaori",
        "lastName": "Naomi",
        "email": "kaorinaomi@example.com",
        "birthDate": "Thu Jun 07 1990",
        "basicSalary": 53934,
        "status": "Active",
        "group": "UI/UX Design",
        "description": "Jangan hanya bekerja keras, tapi juga bekerja cerdas"
    },
    {
        "id": "a6c89bc8-832d-49b3-8e58-d09b0e039981",
        "position": 67,
        "username": "riko",
        "firstName": "Riko",
        "lastName": "Minami",
        "email": "rikominami@example.com",
        "birthDate": "Mon Apr 13 1987",
        "basicSalary": 30715,
        "status": "Probation",
        "group": "HR",
        "description": "Bersyukur atas apa yang dimiliki hari ini adalah kunci kebahagiaan"
    },
    {
        "id": "bcdbeff3-6d51-49de-9549-dbcb283b067c",
        "position": 68,
        "username": "haruki",
        "firstName": "Haruki",
        "lastName": "Sho",
        "email": "harukisho@example.com",
        "birthDate": "Thu Dec 17 1987",
        "basicSalary": 55031,
        "status": "Training",
        "group": "Sales",
        "description": "Jangan hanya bekerja untuk uang, tapi juga untuk kepuasan diri"
    },
    {
        "id": "b284cc9f-3fae-4958-b275-ce29c8470171",
        "position": 69,
        "username": "shinichi",
        "firstName": "Shinichi",
        "lastName": "Tetsuo",
        "email": "shinichitetsuo@example.com",
        "birthDate": "Mon Oct 19 1998",
        "basicSalary": 69653,
        "status": "Layoff",
        "group": "Public Relations",
        "description": "Setiap orang punya waktunya masing-masing untuk sukses"
    },
    {
        "id": "d92f77c3-adfc-4b0d-a269-0fe255fbd3bf",
        "position": 70,
        "username": "masaru",
        "firstName": "Masaru",
        "lastName": "Kenta",
        "email": "masarukenta@example.com",
        "birthDate": "Fri Jul 09 1993",
        "basicSalary": 115421,
        "status": "Freelancer",
        "group": "Sales",
        "description": "Ketekunan adalah rahasia dari banyak keberhasilan"
    },
    {
        "id": "120fb8b0-ca8c-4e10-a0fe-df9672d09849",
        "position": 71,
        "username": "takumi",
        "firstName": "Takumi",
        "lastName": "Daichi",
        "email": "takumidaichi@example.com",
        "birthDate": "Tue Jun 24 2003",
        "basicSalary": 63070,
        "status": "Training",
        "group": "Public Relations",
        "description": "Sabar dalam proses, karena hasil akan datang pada waktunya"
    },
    {
        "id": "ae88ce2b-18dd-4256-8756-38caf05c0961",
        "position": 72,
        "username": "kazuki",
        "firstName": "Kazuki",
        "lastName": "Natsuo",
        "email": "kazukinatsuo@example.com",
        "birthDate": "Tue Jun 11 1985",
        "basicSalary": 44245,
        "status": "Contract Ended",
        "group": "Software Development",
        "description": "Jadilah pemimpin yang menginspirasi, bukan sekadar memberi perintah"
    },
    {
        "id": "9921460e-8c29-4f14-b596-1c2ae3ca0075",
        "position": 73,
        "username": "ahmed",
        "firstName": "Ahmed",
        "lastName": "Hassan",
        "email": "ahmedhassan@example.com",
        "birthDate": "Fri Mar 18 1988",
        "basicSalary": 57321,
        "status": "Suspended",
        "group": "Sales",
        "description": "Jangan hanya bermimpi, tapi wujudkan dengan tindakan nyata"
    },
    {
        "id": "6ff59784-009a-4fde-9107-ca5c29eea1dd",
        "position": 74,
        "username": "omar",
        "firstName": "Omar",
        "lastName": "Yusuf",
        "email": "omaryusuf@example.com",
        "birthDate": "Thu Oct 15 1992",
        "basicSalary": 81903,
        "status": "Contract Ended",
        "group": "Public Relations",
        "description": "Hasil tidak mengkhianati usaha"
    },
    {
        "id": "48600d40-d888-4642-ae50-d7aa260d7998",
        "position": 75,
        "username": "karim",
        "firstName": "Karim",
        "lastName": "Ibrahim",
        "email": "karimibrahim@example.com",
        "birthDate": "Fri Feb 07 1992",
        "basicSalary": 59125,
        "status": "Terminated",
        "group": "Network Engineering",
        "description": "Jangan takut mencoba hal baru"
    },
    {
        "id": "ae8bfd97-0a51-4c56-8c86-bddaa7ce904d",
        "position": 76,
        "username": "tariq",
        "firstName": "Tariq",
        "lastName": "Sami",
        "email": "tariqsami@example.com",
        "birthDate": "Tue Feb 28 1989",
        "basicSalary": 52170,
        "status": "Available for Hire",
        "group": "Sales",
        "description": "Saling mendukung akan membawa tim ke level lebih tinggi"
    },
    {
        "id": "9a61c2f3-866a-4a05-a8a7-7fcb47e3b863",
        "position": 77,
        "username": "zaid",
        "firstName": "Zaid",
        "lastName": "Abdullah",
        "email": "zaidabdullah@example.com",
        "birthDate": "Thu Oct 12 1989",
        "basicSalary": 87177,
        "status": "Intern",
        "group": "Finance",
        "description": "Jangan hanya bekerja keras, tapi juga bekerja cerdas"
    },
    {
        "id": "01ebcff0-b467-4ae1-a761-45c4bfc1b7e4",
        "position": 78,
        "username": "aisha",
        "firstName": "Aisha",
        "lastName": "Fatima",
        "email": "aishafatima@example.com",
        "birthDate": "Fri Sep 03 1999",
        "basicSalary": 104087,
        "status": "Contract Ended",
        "group": "Network Engineering",
        "description": "Jangan hanya bermimpi, tapi wujudkan dengan tindakan nyata"
    },
    {
        "id": "a6ec41cc-f0f8-4cb7-8f6e-84dbb491ee16",
        "position": 79,
        "username": "layla",
        "firstName": "Layla",
        "lastName": "Zahra",
        "email": "laylazahra@example.com",
        "birthDate": "Mon Mar 25 2002",
        "basicSalary": 97322,
        "status": "Sabbatical",
        "group": "Customer Service",
        "description": "Tantangan yang sulit akan membuatmu lebih kuat"
    },
    {
        "id": "af3dbf91-7c2e-41ac-ad6c-5c491e7b4c5d",
        "position": 80,
        "username": "noor",
        "firstName": "Noor",
        "lastName": "Nadia",
        "email": "noornadia@example.com",
        "birthDate": "Wed Nov 17 1999",
        "basicSalary": 92262,
        "status": "On Leave",
        "group": "UI/UX Design",
        "description": "Keahlian tidak datang secara instan, teruslah berlatih"
    },
    {
        "id": "8d4b8672-11fd-4acf-8e4b-1a47af251a76",
        "position": 81,
        "username": "salma",
        "firstName": "Salma",
        "lastName": "Hafsa",
        "email": "salmahafsa@example.com",
        "birthDate": "Fri May 01 1992",
        "basicSalary": 67154,
        "status": "Suspended",
        "group": "HR",
        "description": "Kepercayaan diri adalah awal dari kesuksesan"
    },
    {
        "id": "04cc7df8-8ba0-4321-b0fa-653d01f90051",
        "position": 82,
        "username": "sofia",
        "firstName": "Sofia",
        "lastName": "Amira",
        "email": "sofiaamira@example.com",
        "birthDate": "Mon Oct 06 1997",
        "basicSalary": 41388,
        "status": "Inactive",
        "group": "Customer Service",
        "description": "Kerja keras hari ini adalah investasi untuk masa depan"
    },
    {
        "id": "671877a3-1d75-4abb-a393-4659bc924ad9",
        "position": 83,
        "username": "ali",
        "firstName": "Ali",
        "lastName": "Reza",
        "email": "alireza@example.com",
        "birthDate": "Fri Oct 27 2000",
        "basicSalary": 86270,
        "status": "Active",
        "group": "Finance",
        "description": "Tantangan yang sulit akan membuatmu lebih kuat"
    },
    {
        "id": "4495edc7-e9b1-4997-aebc-1ba553c2e6d3",
        "position": 84,
        "username": "hassan",
        "firstName": "Hassan",
        "lastName": "Farid",
        "email": "hassanfarid@example.com",
        "birthDate": "Fri Dec 27 1985",
        "basicSalary": 105533,
        "status": "Sabbatical",
        "group": "Public Relations",
        "description": "Jadilah pemimpin yang menginspirasi, bukan sekadar memberi perintah"
    },
    {
        "id": "1bb83bf5-d52b-4ef5-a603-140177ede235",
        "position": 85,
        "username": "jamal",
        "firstName": "Jamal",
        "lastName": "Rashid",
        "email": "jamalrashid@example.com",
        "birthDate": "Tue Apr 27 2004",
        "basicSalary": 74325,
        "status": "Sabbatical",
        "group": "HR",
        "description": "Semangat tidak boleh luntur meski tantangan datang"
    },
    {
        "id": "0677afcd-1900-4024-8440-fa74ff398fa9",
        "position": 86,
        "username": "nasir",
        "firstName": "Nasir",
        "lastName": "Khalil",
        "email": "nasirkhalil@example.com",
        "birthDate": "Fri Jul 25 2003",
        "basicSalary": 63740,
        "status": "On Leave",
        "group": "Network Engineering",
        "description": "Tidak ada jalan pintas menuju kesuksesan, semua butuh usaha"
    },
    {
        "id": "3d28b04c-f60e-43ee-b400-0d1b996f2e94",
        "position": 87,
        "username": "yusuf",
        "firstName": "Yusuf",
        "lastName": "Tariq",
        "email": "yusuftariq@example.com",
        "birthDate": "Sat Mar 19 1988",
        "basicSalary": 108337,
        "status": "Contract Ended",
        "group": "Finance",
        "description": "Kedisiplinan adalah kunci keberhasilan jangka panjang"
    },
    {
        "id": "b83d1290-4dd7-4847-a73c-21d5348899fa",
        "position": 88,
        "username": "carlos",
        "firstName": "Carlos",
        "lastName": "Eduardo",
        "email": "carloseduardo@example.com",
        "birthDate": "Sun Feb 28 1988",
        "basicSalary": 42091,
        "status": "Probation",
        "group": "UI/UX Design",
        "description": "Coding adalah seni yang terus berkembang"
    },
    {
        "id": "c9496ff7-fb26-4692-b12b-4d1ed97c1d60",
        "position": 89,
        "username": "jose",
        "firstName": "Jose",
        "lastName": "Manuel",
        "email": "josemanuel@example.com",
        "birthDate": "Sun Mar 10 1996",
        "basicSalary": 103259,
        "status": "Active",
        "group": "Public Relations",
        "description": "Teruslah berkembang dan beradaptasi dengan perubahan"
    },
    {
        "id": "e3b5052d-2df0-4add-b559-0b8fea15bd0d",
        "position": 90,
        "username": "francisco",
        "firstName": "Francisco",
        "lastName": "Antonio",
        "email": "franciscoantonio@example.com",
        "birthDate": "Wed Apr 04 2001",
        "basicSalary": 48879,
        "status": "Part-Time",
        "group": "Customer Service",
        "description": "Tantangan adalah peluang untuk berkembang"
    },
    {
        "id": "ba9f6017-fef0-4419-86ba-04171a9619f3",
        "position": 91,
        "username": "diego",
        "firstName": "Diego",
        "lastName": "Santiago",
        "email": "diegosantiago@example.com",
        "birthDate": "Wed May 16 2001",
        "basicSalary": 99230,
        "status": "Probation",
        "group": "DevOps",
        "description": "Ketika merasa lelah, ingat kembali tujuan awalmu"
    },
    {
        "id": "59475ddd-5fff-48d2-9899-4519e7cf2b4f",
        "position": 92,
        "username": "luis",
        "firstName": "Luis",
        "lastName": "Fernando",
        "email": "luisfernando@example.com",
        "birthDate": "Sun Apr 23 2000",
        "basicSalary": 50603,
        "status": "Training",
        "group": "UI/UX Design",
        "description": "Bekerja dengan hati akan memberikan hasil yang luar biasa"
    },
    {
        "id": "db7731f3-52ea-4657-8598-afc5bf2f3f44",
        "position": 93,
        "username": "maria",
        "firstName": "Maria",
        "lastName": "Camila",
        "email": "mariacamila@example.com",
        "birthDate": "Fri Oct 22 1993",
        "basicSalary": 105186,
        "status": "Medical Leave",
        "group": "HR",
        "description": "Jangan hanya bekerja keras, tapi juga bekerja cerdas"
    },
    {
        "id": "7495ca2b-cf4d-4e82-89d6-d3c656667c3c",
        "position": 94,
        "username": "gabriela",
        "firstName": "Gabriela",
        "lastName": "Isabel",
        "email": "gabrielaisabel@example.com",
        "birthDate": "Thu Feb 28 1985",
        "basicSalary": 57515,
        "status": "Suspended",
        "group": "Public Relations",
        "description": "Jangan hanya bermimpi, tapi wujudkan dengan tindakan nyata"
    },
    {
        "id": "c97aad0a-2277-496f-bc3b-91c1aa119f74",
        "position": 95,
        "username": "valentina",
        "firstName": "Valentina",
        "lastName": "Lucia",
        "email": "valentinalucia@example.com",
        "birthDate": "Fri Jul 22 1994",
        "basicSalary": 92675,
        "status": "Contract Ended",
        "group": "Customer Service",
        "description": "Belajar dari orang lain adalah cara terbaik untuk berkembang"
    },
    {
        "id": "3b98450e-bf73-45ef-a126-a221bfa0ec09",
        "position": 96,
        "username": "ana",
        "firstName": "Ana",
        "lastName": "Fernanda",
        "email": "anafernanda@example.com",
        "birthDate": "Wed Mar 25 1992",
        "basicSalary": 107185,
        "status": "Transferred",
        "group": "Software Development",
        "description": "Kreativitas tidak memiliki batas"
    },
    {
        "id": "36cdbe85-129a-40f8-82d2-798c68566d52",
        "position": 97,
        "username": "paola",
        "firstName": "Paola",
        "lastName": "Andrea",
        "email": "paolaandrea@example.com",
        "birthDate": "Tue Mar 12 1996",
        "basicSalary": 98022,
        "status": "Sabbatical",
        "group": "Customer Service",
        "description": "Kepercayaan diri adalah awal dari kesuksesan"
    },
    {
        "id": "a4190e30-4793-48d5-9391-7cec301200c1",
        "position": 98,
        "username": "enrique",
        "firstName": "Enrique",
        "lastName": "Javier",
        "email": "enriquejavier@example.com",
        "birthDate": "Mon Mar 22 2004",
        "basicSalary": 37610,
        "status": "Available for Hire",
        "group": "Finance",
        "description": "Jangan hanya bekerja keras, tapi juga bekerja cerdas"
    },
    {
        "id": "12639b6a-f29e-4aeb-b808-3bf968ba9833",
        "position": 99,
        "username": "raul",
        "firstName": "Raul",
        "lastName": "Esteban",
        "email": "raulesteban@example.com",
        "birthDate": "Wed Oct 15 1997",
        "basicSalary": 102635,
        "status": "Intern",
        "group": "Software Development",
        "description": "Kedisiplinan adalah kunci keberhasilan jangka panjang"
    },
    {
        "id": "331de75d-215b-412d-a0aa-83d5dd724e27",
        "position": 100,
        "username": "miguel",
        "firstName": "Miguel",
        "lastName": "Andres",
        "email": "miguelandres@example.com",
        "birthDate": "Tue Sep 28 2004",
        "basicSalary": 33169,
        "status": "Part-Time",
        "group": "Public Relations",
        "description": "Kedisiplinan adalah kunci keberhasilan jangka panjang"
    },
    {
        "id": "1d0cc987-6fcf-4036-9faa-220a68d2e97d",
        "position": 101,
        "username": "fernando",
        "firstName": "Fernando",
        "lastName": "Mateo",
        "email": "fernandomateo@example.com",
        "birthDate": "Mon Feb 16 2004",
        "basicSalary": 63734,
        "status": "Active",
        "group": "Customer Service",
        "description": "Teruslah berkembang dan beradaptasi dengan perubahan"
    },
    {
        "id": "a98155d0-401c-4b50-abed-846715f2b502",
        "position": 102,
        "username": "ricardo",
        "firstName": "Ricardo",
        "lastName": "Emilio",
        "email": "ricardoemilio@example.com",
        "birthDate": "Sun Aug 25 1996",
        "basicSalary": 88376,
        "status": "Suspended",
        "group": "Finance",
        "description": "Kunci kebahagiaan adalah bersyukur dalam setiap keadaan"
    },
    {
        "id": "152d294b-9675-4bea-a175-275df7c4eb36",
        "position": 103,
        "username": "liam",
        "firstName": "Liam",
        "lastName": "Jackson",
        "email": "liamjackson@example.com",
        "birthDate": "Sat Aug 24 1991",
        "basicSalary": 34576,
        "status": "Part-Time",
        "group": "Customer Service",
        "description": "Tindakan kecil hari ini akan membawa perubahan besar di masa depan"
    },
    {
        "id": "ac2ea770-cef3-46e5-a412-9c8f290c45d0",
        "position": 104,
        "username": "noah",
        "firstName": "Noah",
        "lastName": "Carter",
        "email": "noahcarter@example.com",
        "birthDate": "Thu May 25 1989",
        "basicSalary": 94349,
        "status": "Freelancer",
        "group": "Software Development",
        "description": "Bekerja dengan semangat dan dedikasi"
    },
    {
        "id": "cb043a8d-ca68-493b-888c-909f906004b6",
        "position": 105,
        "username": "logan",
        "firstName": "Logan",
        "lastName": "Hunter",
        "email": "loganhunter@example.com",
        "birthDate": "Mon Jan 04 1993",
        "basicSalary": 65515,
        "status": "Inactive",
        "group": "Public Relations",
        "description": "Sabar dalam proses, karena hasil akan datang pada waktunya"
    },
    {
        "id": "3d75b2b8-56da-4779-be74-12c4a8d88f02",
        "position": 106,
        "username": "mason",
        "firstName": "Mason",
        "lastName": "Wyatt",
        "email": "masonwyatt@example.com",
        "birthDate": "Fri May 08 1992",
        "basicSalary": 51120,
        "status": "Temporary",
        "group": "Network Engineering",
        "description": "Setiap masalah punya solusi, hanya perlu dicari dengan sabar"
    },
    {
        "id": "add013b4-550c-4128-9489-b4333062ccd1",
        "position": 107,
        "username": "elijah",
        "firstName": "Elijah",
        "lastName": "Jordan",
        "email": "elijahjordan@example.com",
        "birthDate": "Thu Sep 06 1990",
        "basicSalary": 85244,
        "status": "Contract Ended",
        "group": "Finance",
        "description": "Ketika merasa lelah, ingat kembali tujuan awalmu"
    },
    {
        "id": "23844dbc-28d6-48ce-ab09-c35cd4bc906e",
        "position": 108,
        "username": "zoe",
        "firstName": "Zoe",
        "lastName": "Alexandra",
        "email": "zoealexandra@example.com",
        "birthDate": "Tue Apr 18 1989",
        "basicSalary": 64203,
        "status": "Intern",
        "group": "Public Relations",
        "description": "Jangan hanya bekerja keras, tapi juga bekerja cerdas"
    },
    {
        "id": "c0cbd51a-e5a1-4f3d-a81b-35b0949f3982",
        "position": 109,
        "username": "mia",
        "firstName": "Mia",
        "lastName": "Isabella",
        "email": "miaisabella@example.com",
        "birthDate": "Wed Dec 24 2003",
        "basicSalary": 38096,
        "status": "Probation",
        "group": "Finance",
        "description": "Ketika ragu, ingatlah alasanmu memulai"
    },
    {
        "id": "b5ee7829-f861-489a-a2d0-afcf3a2580ae",
        "position": 110,
        "username": "ava",
        "firstName": "Ava",
        "lastName": "Madison",
        "email": "avamadison@example.com",
        "birthDate": "Tue Feb 17 1998",
        "basicSalary": 59554,
        "status": "Medical Leave",
        "group": "UI/UX Design",
        "description": "Komunikasi yang baik membangun hubungan yang kuat"
    },
    {
        "id": "f9ef1981-520e-4347-a872-c45f8ef79852",
        "position": 111,
        "username": "harper",
        "firstName": "Harper",
        "lastName": "Evelyn",
        "email": "harperevelyn@example.com",
        "birthDate": "Tue Dec 18 1990",
        "basicSalary": 57541,
        "status": "Maternity Leave",
        "group": "DevOps",
        "description": "Kualitas lebih penting daripada kuantitas dalam setiap pekerjaan"
    },
    {
        "id": "a473481a-687a-43bb-955f-a09fa1be6e0f",
        "position": 112,
        "username": "scarlett",
        "firstName": "Scarlett",
        "lastName": "Aurora",
        "email": "scarlettaurora@example.com",
        "birthDate": "Thu Jan 12 1989",
        "basicSalary": 30720,
        "status": "Intern",
        "group": "Customer Service",
        "description": "Bersyukur atas apa yang dimiliki hari ini adalah kunci kebahagiaan"
    },
    {
        "id": "67bc4f2f-bb78-42df-8917-bb5e320cdf84",
        "position": 113,
        "username": "ethan",
        "firstName": "Ethan",
        "lastName": "Blake",
        "email": "ethanblake@example.com",
        "birthDate": "Fri Dec 05 1997",
        "basicSalary": 106737,
        "status": "Inactive",
        "group": "Sales",
        "description": "Pikiran positif membawa kehidupan yang lebih baik"
    },
    {
        "id": "2acfbf78-63b7-45dc-a053-7cd2b4fb784a",
        "position": 114,
        "username": "owen",
        "firstName": "Owen",
        "lastName": "Parker",
        "email": "owenparker@example.com",
        "birthDate": "Wed Jul 26 1989",
        "basicSalary": 31083,
        "status": "Active",
        "group": "DevOps",
        "description": "Belajar dari kegagalan adalah kunci sukses"
    },
    {
        "id": "453a2dc7-ad67-4c14-b7da-8da13357b4cb",
        "position": 115,
        "username": "caleb",
        "firstName": "Caleb",
        "lastName": "Hudson",
        "email": "calebhudson@example.com",
        "birthDate": "Wed May 05 2004",
        "basicSalary": 30825,
        "status": "Intern",
        "group": "Public Relations",
        "description": "Teknologi terus berubah, tetaplah beradaptasi"
    },
    {
        "id": "6e4bf986-596a-4931-b551-956327c19c5d",
        "position": 116,
        "username": "henry",
        "firstName": "Henry",
        "lastName": "Finn",
        "email": "henryfinn@example.com",
        "birthDate": "Tue Aug 26 1997",
        "basicSalary": 67287,
        "status": "Probation",
        "group": "Public Relations",
        "description": "Tantangan yang sulit akan membuatmu lebih kuat"
    },
    {
        "id": "361e2b8a-9af2-4f14-b5dd-dfb9cfd3e800",
        "position": 117,
        "username": "lucas",
        "firstName": "Lucas",
        "lastName": "Xavier",
        "email": "lucasxavier@example.com",
        "birthDate": "Sun May 28 1989",
        "basicSalary": 114977,
        "status": "Inactive",
        "group": "Software Development",
        "description": "Kesuksesan tidak datang dengan sendirinya, tapi dari usaha dan doa"
    },
    {
        "id": "2667ba0c-57fd-4d18-8d6f-7cf615142f96",
        "position": 118,
        "username": "nathaniel",
        "firstName": "Nathaniel",
        "lastName": "Blake",
        "email": "nathanielblake@example.com",
        "birthDate": "Thu Jun 04 1998",
        "basicSalary": 35939,
        "status": "Medical Leave",
        "group": "Sales",
        "description": "Jangan hanya bermimpi, tapi wujudkan dengan tindakan nyata"
    },
    {
        "id": "949d1fb1-2cca-4c17-a9f7-e2064c3c1364",
        "position": 119,
        "username": "oliver",
        "firstName": "Oliver",
        "lastName": "Hudson",
        "email": "oliverhudson@example.com",
        "birthDate": "Mon Nov 22 1993",
        "basicSalary": 74681,
        "status": "Terminated",
        "group": "Customer Service",
        "description": "Jangan biarkan kritik menghentikan langkahmu, jadikan sebagai motivasi"
    },
    {
        "id": "5b7e397c-6d14-4044-91b3-e6600cdfbd6e",
        "position": 120,
        "username": "jonathan",
        "firstName": "Jonathan",
        "lastName": "Reese",
        "email": "jonathanreese@example.com",
        "birthDate": "Sun Mar 23 1986",
        "basicSalary": 104032,
        "status": "On Leave",
        "group": "DevOps",
        "description": "Tidak ada batasan untuk belajar dan berkembang"
    },
    {
        "id": "10c2c80a-3d13-4ab2-907c-3409d9a599ce",
        "position": 121,
        "username": "samuel",
        "firstName": "Samuel",
        "lastName": "Xavier",
        "email": "samuelxavier@example.com",
        "birthDate": "Sun Mar 24 2002",
        "basicSalary": 38736,
        "status": "Freelancer",
        "group": "HR",
        "description": "Teruslah berjuang meski jalan terasa berat"
    },
    {
        "id": "7a3768db-b00a-4fbf-885d-b912b0feff3e",
        "position": 122,
        "username": "henry",
        "firstName": "Henry",
        "lastName": "Finn",
        "email": "henryfinn@example.com",
        "birthDate": "Sat Feb 25 1995",
        "basicSalary": 37805,
        "status": "Active",
        "group": "Finance",
        "description": "Coding adalah seni yang terus berkembang"
    },
    {
        "id": "ba2e0f1a-25d8-4ab5-a835-139e12e7a791",
        "position": 123,
        "username": "chloe",
        "firstName": "Chloe",
        "lastName": "Beatrice",
        "email": "chloebeatrice@example.com",
        "birthDate": "Tue Mar 19 2002",
        "basicSalary": 109888,
        "status": "Maternity Leave",
        "group": "UI/UX Design",
        "description": "Jangan pernah berhenti untuk bermimpi"
    },
    {
        "id": "a0f4f4f4-2c78-488d-9a01-17c54354214a",
        "position": 124,
        "username": "victoria",
        "firstName": "Victoria",
        "lastName": "Celeste",
        "email": "victoriaceleste@example.com",
        "birthDate": "Mon Jun 14 1993",
        "basicSalary": 79732,
        "status": "Sabbatical",
        "group": "Network Engineering",
        "description": "Kesuksesan tidak datang dengan sendirinya, tapi dari usaha dan doa"
    },
    {
        "id": "f833f8ba-176d-4ed0-95a5-82f81b6cdd54",
        "position": 125,
        "username": "penelope",
        "firstName": "Penelope",
        "lastName": "Jade",
        "email": "penelopejade@example.com",
        "birthDate": "Mon Feb 15 1993",
        "basicSalary": 103889,
        "status": "Remote",
        "group": "HR",
        "description": "Jangan menunda pekerjaan, karena waktu tidak bisa diulang"
    },
    {
        "id": "3f0cb5bb-8bdf-4edf-91f7-0fe3c69de64d",
        "position": 126,
        "username": "savannah",
        "firstName": "Savannah",
        "lastName": "Elise",
        "email": "savannahelise@example.com",
        "birthDate": "Wed Jun 04 1986",
        "basicSalary": 41320,
        "status": "Intern",
        "group": "Network Engineering",
        "description": "Teknologi terus berubah, tetaplah beradaptasi"
    },
    {
        "id": "870eb966-d440-45e0-a23b-0ecb6416fa54",
        "position": 127,
        "username": "madeline",
        "firstName": "Madeline",
        "lastName": "Violet",
        "email": "madelineviolet@example.com",
        "birthDate": "Sun Feb 28 1999",
        "basicSalary": 84820,
        "status": "Terminated",
        "group": "DevOps",
        "description": "Mimpi besar membutuhkan usaha besar"
    },
    {
        "id": "613a44fc-42e4-4d32-8e6b-5e7def36ec3c",
        "position": 128,
        "username": "asher",
        "firstName": "Asher",
        "lastName": "Zane",
        "email": "asherzane@example.com",
        "birthDate": "Tue Dec 07 1993",
        "basicSalary": 75830,
        "status": "Transferred",
        "group": "Customer Service",
        "description": "Membangun masa depan yang lebih baik"
    },
    {
        "id": "4bae8f31-49f4-42a0-95bf-d9a90a4157c4",
        "position": 129,
        "username": "wyatt",
        "firstName": "Wyatt",
        "lastName": "Nolan",
        "email": "wyattnolan@example.com",
        "birthDate": "Wed Mar 15 2000",
        "basicSalary": 69916,
        "status": "Consultant",
        "group": "UI/UX Design",
        "description": "Dunia terus bergerak, jangan sampai tertinggal"
    },
    {
        "id": "ebe7a3a6-9eeb-4a16-a85f-d9a1a1a48dca",
        "position": 130,
        "username": "ronan",
        "firstName": "Ronan",
        "lastName": "Jasper",
        "email": "ronanjasper@example.com",
        "birthDate": "Thu Jun 12 1997",
        "basicSalary": 69208,
        "status": "Training",
        "group": "Network Engineering",
        "description": "Kreativitas tidak memiliki batas"
    },
    {
        "id": "fb4eb7ef-0b8e-4818-b511-9828f1852726",
        "position": 131,
        "username": "gideon",
        "firstName": "Gideon",
        "lastName": "Miles",
        "email": "gideonmiles@example.com",
        "birthDate": "Wed Apr 21 2004",
        "basicSalary": 61888,
        "status": "Part-Time",
        "group": "Public Relations",
        "description": "Kualitas lebih penting daripada kuantitas dalam setiap pekerjaan"
    },
    {
        "id": "c26650ed-e2ca-4ff5-aa16-798592a8bf3a",
        "position": 132,
        "username": "silas",
        "firstName": "Silas",
        "lastName": "Roman",
        "email": "silasroman@example.com",
        "birthDate": "Wed Oct 08 2003",
        "basicSalary": 77277,
        "status": "Remote",
        "group": "UI/UX Design",
        "description": "Hargai setiap usaha sekecil apapun, karena itu adalah langkah maju"
    },
    {
        "id": "fb27e58d-63db-4f31-9668-71be5f91f927",
        "position": 133,
        "username": "aragorn",
        "firstName": "Aragorn",
        "lastName": "Elessar",
        "email": "aragornelessar@example.com",
        "birthDate": "Sun Nov 08 1992",
        "basicSalary": 95080,
        "status": "Inactive",
        "group": "Public Relations",
        "description": "Ketika merasa lelah, ingat kembali tujuan awalmu"
    },
    {
        "id": "555df691-30d7-4889-9ad2-efcf7712a061",
        "position": 134,
        "username": "legolas",
        "firstName": "Legolas",
        "lastName": "Greenleaf",
        "email": "legolasgreenleaf@example.com",
        "birthDate": "Sat Oct 10 1998",
        "basicSalary": 60437,
        "status": "On Leave",
        "group": "DevOps",
        "description": "Kunci kebahagiaan adalah bersyukur dalam setiap keadaan"
    },
    {
        "id": "11ef2990-1e02-432e-a48b-97e485f013a7",
        "position": 135,
        "username": "frodo",
        "firstName": "Frodo",
        "lastName": "Baggins",
        "email": "frodobaggins@example.com",
        "birthDate": "Wed Apr 08 1998",
        "basicSalary": 66792,
        "status": "Part-Time",
        "group": "Public Relations",
        "description": "Jangan pernah ragu dengan potensimu sendiri"
    },
    {
        "id": "9bae05d6-6518-4875-9251-c49e6ad694d9",
        "position": 136,
        "username": "hermione",
        "firstName": "Hermione",
        "lastName": "Granger",
        "email": "hermionegranger@example.com",
        "birthDate": "Mon Apr 19 1993",
        "basicSalary": 75772,
        "status": "Inactive",
        "group": "Finance",
        "description": "Berani keluar dari zona nyaman adalah langkah awal menuju perubahan"
    },
    {
        "id": "7bcb6cb6-8124-489d-932e-5059af015a49",
        "position": 137,
        "username": "albus",
        "firstName": "Albus",
        "lastName": "Dumbledore",
        "email": "albusdumbledore@example.com",
        "birthDate": "Thu Jul 06 1989",
        "basicSalary": 117972,
        "status": "Suspended",
        "group": "UI/UX Design",
        "description": "Tidak ada jalan pintas menuju kesuksesan, semua butuh usaha"
    },
    {
        "id": "bc497e52-8b6f-479d-9e29-502010bbe71a",
        "position": 138,
        "username": "daenerys",
        "firstName": "Daenerys",
        "lastName": "Targaryen",
        "email": "daenerystargaryen@example.com",
        "birthDate": "Sun Apr 28 1991",
        "basicSalary": 36240,
        "status": "Retired",
        "group": "Technical Support",
        "description": "Coding adalah seni yang terus berkembang"
    },
    {
        "id": "e0f77d21-ac08-4105-8e74-02cc8e0fc840",
        "position": 139,
        "username": "jon",
        "firstName": "Jon",
        "lastName": "Snow",
        "email": "jonsnow@example.com",
        "birthDate": "Tue Feb 10 2004",
        "basicSalary": 94279,
        "status": "Dismissed",
        "group": "DevOps",
        "description": "Kesuksesan tidak datang dengan sendirinya, tapi dari usaha dan doa"
    },
    {
        "id": "5e869657-3661-4a04-80a8-648c96ffb613",
        "position": 140,
        "username": "tyrion",
        "firstName": "Tyrion",
        "lastName": "Lannister",
        "email": "tyrionlannister@example.com",
        "birthDate": "Thu Oct 03 2002",
        "basicSalary": 108120,
        "status": "Retired",
        "group": "Public Relations",
        "description": "Percaya pada diri sendiri adalah langkah pertama menuju keberhasilan"
    },
    {
        "id": "3204a116-a604-4973-963a-bdd07416f004",
        "position": 141,
        "username": "eowyn",
        "firstName": "Eowyn",
        "lastName": "Rohan",
        "email": "eowynrohan@example.com",
        "birthDate": "Wed Jul 01 1998",
        "basicSalary": 46844,
        "status": "Medical Leave",
        "group": "DevOps",
        "description": "Belajar dari kegagalan adalah kunci sukses"
    },
    {
        "id": "e7ce8318-556d-4c21-92cb-734d32526904",
        "position": 142,
        "username": "gandalf",
        "firstName": "Gandalf",
        "lastName": "Greyhame",
        "email": "gandalfgreyhame@example.com",
        "birthDate": "Sun Sep 27 1998",
        "basicSalary": 56821,
        "status": "Dismissed",
        "group": "UI/UX Design",
        "description": "Berpikirlah positif, karena pikiran adalah awal dari segalanya"
    },
    {
        "id": "de8c436d-b17b-4147-b5e1-dd1e0e8f8124",
        "position": 143,
        "username": "draco",
        "firstName": "Draco",
        "lastName": "Malfoy",
        "email": "dracomalfoy@example.com",
        "birthDate": "Wed Sep 03 1997",
        "basicSalary": 53153,
        "status": "Intern",
        "group": "Network Engineering",
        "description": "Teruslah berkembang dan beradaptasi dengan perubahan"
    },
    {
        "id": "bdd4ca68-3c55-4231-92f8-e15d12ed3763",
        "position": 144,
        "username": "luna",
        "firstName": "Luna",
        "lastName": "Lovegood",
        "email": "lunalovegood@example.com",
        "birthDate": "Mon Aug 03 1992",
        "basicSalary": 78365,
        "status": "Suspended",
        "group": "Software Development",
        "description": "Kerja keras hari ini adalah investasi untuk masa depan"
    },
    {
        "id": "34c1df37-86f4-4bdb-9761-e453d4ba9af8",
        "position": 145,
        "username": "severus",
        "firstName": "Severus",
        "lastName": "Snape",
        "email": "severussnape@example.com",
        "birthDate": "Sat Jan 04 2003",
        "basicSalary": 35760,
        "status": "Remote",
        "group": "Customer Service",
        "description": "Berpikirlah positif, karena pikiran adalah awal dari segalanya"
    },
    {
        "id": "d816df8f-c15b-4661-bc87-cd8d3c7cfc98",
        "position": 146,
        "username": "sirius",
        "firstName": "Sirius",
        "lastName": "Black",
        "email": "siriusblack@example.com",
        "birthDate": "Sun Sep 15 1985",
        "basicSalary": 101932,
        "status": "Available for Hire",
        "group": "UI/UX Design",
        "description": "Setiap hari adalah kesempatan untuk belajar"
    },
    {
        "id": "2e1c74f6-5f5a-4ec2-b058-9e32d88fecdc",
        "position": 147,
        "username": "remus",
        "firstName": "Remus",
        "lastName": "Lupin",
        "email": "remuslupin@example.com",
        "birthDate": "Tue Sep 13 1994",
        "basicSalary": 33217,
        "status": "Maternity Leave",
        "group": "DevOps",
        "description": "Jangan takut gagal, karena setiap kegagalan adalah pengalaman"
    },
    {
        "id": "e1c6265c-b752-4017-87f4-4480703b5bb2",
        "position": 148,
        "username": "marco",
        "firstName": "Marco",
        "lastName": "Antonio",
        "email": "marcoantonio@example.com",
        "birthDate": "Fri Jul 15 1988",
        "basicSalary": 34098,
        "status": "Dismissed",
        "group": "Technical Support",
        "description": "Jangan biarkan kritik menghentikan langkahmu, jadikan sebagai motivasi"
    },
    {
        "id": "d2183d5b-bb4d-42ef-99d0-ae1010e568df",
        "position": 149,
        "username": "viktor",
        "firstName": "Viktor",
        "lastName": "Ivanov",
        "email": "viktorivanov@example.com",
        "birthDate": "Tue Nov 07 1995",
        "basicSalary": 89867,
        "status": "Intern",
        "group": "DevOps",
        "description": "Hasil tidak mengkhianati usaha"
    },
    {
        "id": "87679c3e-f346-430a-aa4a-16b24b815baf",
        "position": 150,
        "username": "artem",
        "firstName": "Artem",
        "lastName": "Sergei",
        "email": "artemsergei@example.com",
        "birthDate": "Thu Aug 08 1991",
        "basicSalary": 112238,
        "status": "Training",
        "group": "Software Development",
        "description": "Setiap orang punya jalannya masing-masing menuju sukses"
    },
    {
        "id": "bb2dc6f4-75ea-46ce-9d4c-fe3d49bda5d7",
        "position": 151,
        "username": "pierre",
        "firstName": "Pierre",
        "lastName": "Louis",
        "email": "pierrelouis@example.com",
        "birthDate": "Wed Mar 01 1989",
        "basicSalary": 58755,
        "status": "Retired",
        "group": "HR",
        "description": "Waktu adalah aset yang paling berharga, gunakan dengan bijak"
    },
    {
        "id": "25e0559d-fe6a-4e3c-a6f9-76deca588b40",
        "position": 152,
        "username": "hans",
        "firstName": "Hans",
        "lastName": "Dieter",
        "email": "hansdieter@example.com",
        "birthDate": "Thu Aug 22 1996",
        "basicSalary": 38078,
        "status": "Layoff",
        "group": "Network Engineering",
        "description": "Jangan hanya bekerja keras, tapi juga nikmati prosesnya"
    },
    {
        "id": "8ff0cd75-b963-48e4-9754-bffeb627d33a",
        "position": 153,
        "username": "krzysztof",
        "firstName": "Krzysztof",
        "lastName": "Marek",
        "email": "krzysztofmarek@example.com",
        "birthDate": "Fri May 16 2003",
        "basicSalary": 119045,
        "status": "Maternity Leave",
        "group": "HR",
        "description": "Jadilah versi terbaik dari dirimu sendiri"
    },
    {
        "id": "e0f30fd7-82b5-42f5-b025-1153f6cc2f97",
        "position": 154,
        "username": "giorgio",
        "firstName": "Giorgio",
        "lastName": "Alberto",
        "email": "giorgioalberto@example.com",
        "birthDate": "Sat Jul 09 1994",
        "basicSalary": 35125,
        "status": "Retired",
        "group": "Sales",
        "description": "Jangan lupa istirahat dan tetap sehat"
    },
    {
        "id": "fd7a7656-d177-4428-af4c-77e2ea282fd9",
        "position": 155,
        "username": "mateo",
        "firstName": "Mateo",
        "lastName": "Rafael",
        "email": "mateorafael@example.com",
        "birthDate": "Fri Mar 12 1993",
        "basicSalary": 35087,
        "status": "Resigned",
        "group": "Software Development",
        "description": "Mimpi besar membutuhkan usaha besar"
    },
    {
        "id": "a2171763-4783-457a-82db-c25c3411a1c2",
        "position": 156,
        "username": "juan",
        "firstName": "Juan",
        "lastName": "Pablo",
        "email": "juanpablo@example.com",
        "birthDate": "Wed Oct 16 1991",
        "basicSalary": 78533,
        "status": "Freelancer",
        "group": "HR",
        "description": "Kepercayaan diri adalah awal dari kesuksesan"
    },
    {
        "id": "9cd8f151-dd9f-410b-a4f6-e0abc3f4074c",
        "position": 157,
        "username": "pedro",
        "firstName": "Pedro",
        "lastName": "Enrique",
        "email": "pedroenrique@example.com",
        "birthDate": "Mon Apr 08 2002",
        "basicSalary": 94175,
        "status": "Remote",
        "group": "HR",
        "description": "Semangat tidak boleh luntur meski tantangan datang"
    },
    {
        "id": "9ef3d8bb-d944-4f55-822b-e6db40eb66bc",
        "position": 158,
        "username": "nikolai",
        "firstName": "Nikolai",
        "lastName": "Dimitri",
        "email": "nikolaidimitri@example.com",
        "birthDate": "Sun Jul 26 1987",
        "basicSalary": 40517,
        "status": "Sabbatical",
        "group": "Network Engineering",
        "description": "Mimpi besar hanya bisa diwujudkan dengan aksi nyata"
    },
    {
        "id": "073d6a94-d642-4385-961c-061403b895b6",
        "position": 159,
        "username": "leandro",
        "firstName": "Leandro",
        "lastName": "Gustavo",
        "email": "leandrogustavo@example.com",
        "birthDate": "Sun Oct 04 1992",
        "basicSalary": 48210,
        "status": "Retired",
        "group": "Public Relations",
        "description": "Setiap hari adalah kesempatan untuk belajar"
    },
    {
        "id": "572430b9-4a1a-4828-bbac-dbf54cb4012f",
        "position": 160,
        "username": "thiago",
        "firstName": "Thiago",
        "lastName": "Felipe",
        "email": "thiagofelipe@example.com",
        "birthDate": "Fri May 21 2004",
        "basicSalary": 85374,
        "status": "Medical Leave",
        "group": "Sales",
        "description": "Inovasi adalah jalan menuju kemajuan"
    },
    {
        "id": "aac3e72e-e6e9-4eb9-ad4f-656668087ad4",
        "position": 161,
        "username": "anton",
        "firstName": "Anton",
        "lastName": "Vladislav",
        "email": "antonvladislav@example.com",
        "birthDate": "Sun May 08 1988",
        "basicSalary": 40342,
        "status": "Medical Leave",
        "group": "Sales",
        "description": "Jadilah versi terbaik dari dirimu sendiri"
    },
    {
        "id": "ffb14a98-53ca-43a5-823a-cda144a7dde2",
        "position": 162,
        "username": "bastien",
        "firstName": "Bastien",
        "lastName": "Claude",
        "email": "bastienclaude@example.com",
        "birthDate": "Thu Oct 18 2001",
        "basicSalary": 95721,
        "status": "Part-Time",
        "group": "Customer Service",
        "description": "Bersyukur atas apa yang dimiliki hari ini adalah kunci kebahagiaan"
    },
    {
        "id": "a8c0e74c-c41a-44e3-936f-09a848a801e7",
        "position": 163,
        "username": "albert",
        "firstName": "Albert",
        "lastName": "Newton",
        "email": "albertnewton@example.com",
        "birthDate": "Sun Sep 24 2000",
        "basicSalary": 57469,
        "status": "Part-Time",
        "group": "Customer Service",
        "description": "Jangan pernah berhenti untuk bermimpi"
    },
    {
        "id": "7a9c4ae0-8f77-4dbb-a29f-919592bd1e35",
        "position": 164,
        "username": "marie",
        "firstName": "Marie",
        "lastName": "Curie",
        "email": "mariecurie@example.com",
        "birthDate": "Fri Nov 02 2001",
        "basicSalary": 80047,
        "status": "Resigned",
        "group": "Customer Service",
        "description": "Jadilah versi terbaik dari dirimu sendiri"
    },
    {
        "id": "159fdfcc-66f4-4d8b-8e7f-097c89801ccb",
        "position": 165,
        "username": "isaac",
        "firstName": "Isaac",
        "lastName": "Hawking",
        "email": "isaachawking@example.com",
        "birthDate": "Wed Jul 24 2002",
        "basicSalary": 53823,
        "status": "On Leave",
        "group": "Network Engineering",
        "description": "Hello world adalah awal segalanya"
    },
    {
        "id": "958a957b-2469-436b-8689-afc005372686",
        "position": 166,
        "username": "nikola",
        "firstName": "Nikola",
        "lastName": "Tesla",
        "email": "nikolatesla@example.com",
        "birthDate": "Fri Aug 04 2000",
        "basicSalary": 87297,
        "status": "Training",
        "group": "Public Relations",
        "description": "Membantu orang lain adalah cara terbaik untuk menemukan makna hidup"
    },
    {
        "id": "60386baf-5c04-4e22-8b57-ccdccef181d5",
        "position": 167,
        "username": "charles",
        "firstName": "Charles",
        "lastName": "Darwin",
        "email": "charlesdarwin@example.com",
        "birthDate": "Fri Jun 06 2003",
        "basicSalary": 31926,
        "status": "Dismissed",
        "group": "Customer Service",
        "description": "Tetap rendah hati dalam setiap pencapaian"
    },
    {
        "id": "6a0b0495-c866-47a7-9d75-2085d6a2f8b6",
        "position": 168,
        "username": "leonardo",
        "firstName": "Leonardo",
        "lastName": "Vinci",
        "email": "leonardovinci@example.com",
        "birthDate": "Fri Sep 20 1996",
        "basicSalary": 95456,
        "status": "Freelancer",
        "group": "UI/UX Design",
        "description": "Inovasi adalah jalan menuju kemajuan"
    },
    {
        "id": "e55d6454-0717-4884-a3c5-9c4756ebbc35",
        "position": 169,
        "username": "sigmund",
        "firstName": "Sigmund",
        "lastName": "Freud",
        "email": "sigmundfreud@example.com",
        "birthDate": "Thu Jun 06 1985",
        "basicSalary": 83569,
        "status": "Layoff",
        "group": "DevOps",
        "description": "Kreativitas tidak memiliki batas"
    },
    {
        "id": "4f6e7e1e-952b-4c92-ab20-d90a7a9a0560",
        "position": 170,
        "username": "galileo",
        "firstName": "Galileo",
        "lastName": "Kepler",
        "email": "galileokepler@example.com",
        "birthDate": "Fri Feb 13 1987",
        "basicSalary": 51554,
        "status": "Available for Hire",
        "group": "Software Development",
        "description": "Jangan takut untuk memulai sesuatu yang baru"
    },
    {
        "id": "8a6e570e-583a-4399-8a2f-ae4fe3d0b98d",
        "position": 171,
        "username": "ada",
        "firstName": "Ada",
        "lastName": "Lovelace",
        "email": "adalovelace@example.com",
        "birthDate": "Tue Dec 08 1987",
        "basicSalary": 105821,
        "status": "On Leave",
        "group": "Sales",
        "description": "Waktu adalah aset yang paling berharga, gunakan dengan bijak"
    },
    {
        "id": "622ed11f-3cea-46b5-adae-12be904e7efe",
        "position": 172,
        "username": "margaret",
        "firstName": "Margaret",
        "lastName": "Hamilton",
        "email": "margarethamilton@example.com",
        "birthDate": "Tue Apr 18 2000",
        "basicSalary": 94138,
        "status": "Training",
        "group": "DevOps",
        "description": "Orang sukses adalah mereka yang terus belajar tanpa henti"
    },
    {
        "id": "50b140d3-29a8-4ea8-8442-3e1110d733b3",
        "position": 173,
        "username": "jake",
        "firstName": "Jake",
        "lastName": "Ryan",
        "email": "jakeryan@example.com",
        "birthDate": "Tue Feb 18 2003",
        "basicSalary": 45347,
        "status": "Medical Leave",
        "group": "Network Engineering",
        "description": "Jangan hanya bekerja untuk uang, tapi juga untuk kepuasan diri"
    },
    {
        "id": "5e86ccde-8175-4b93-aa87-d9c11e5924be",
        "position": 174,
        "username": "luca",
        "firstName": "Luca",
        "lastName": "Finn",
        "email": "lucafinn@example.com",
        "birthDate": "Mon May 27 2002",
        "basicSalary": 30426,
        "status": "Medical Leave",
        "group": "Public Relations",
        "description": "Kualitas lebih penting daripada kuantitas dalam setiap pekerjaan"
    },
    {
        "id": "823d1604-1fab-4a36-ab33-8da780b50835",
        "position": 175,
        "username": "troy",
        "firstName": "Troy",
        "lastName": "Mason",
        "email": "troymason@example.com",
        "birthDate": "Tue Jun 04 2002",
        "basicSalary": 51498,
        "status": "Temporary",
        "group": "Customer Service",
        "description": "Jangan hanya bekerja keras, tapi juga bekerja cerdas"
    },
    {
        "id": "e9ae1ee2-f928-41b1-81b6-8350655928e3",
        "position": 176,
        "username": "rex",
        "firstName": "Rex",
        "lastName": "Dylan",
        "email": "rexdylan@example.com",
        "birthDate": "Fri Dec 17 2004",
        "basicSalary": 100189,
        "status": "Layoff",
        "group": "Software Development",
        "description": "Tidak ada jalan pintas menuju kesuksesan, semua butuh usaha"
    },
    {
        "id": "b8090ebb-fdd0-46df-a45e-c981f62d9fa1",
        "position": 177,
        "username": "zane",
        "firstName": "Zane",
        "lastName": "Carter",
        "email": "zanecarter@example.com",
        "birthDate": "Mon Oct 14 1991",
        "basicSalary": 101985,
        "status": "Maternity Leave",
        "group": "Customer Service",
        "description": "Tetap semangat meskipun tantangan terus berdatangan"
    },
    {
        "id": "cc5dc4a6-8a99-4968-9018-154a29bd8182",
        "position": 178,
        "username": "cole",
        "firstName": "Cole",
        "lastName": "Jasper",
        "email": "colejasper@example.com",
        "birthDate": "Fri Mar 01 1996",
        "basicSalary": 78133,
        "status": "Intern",
        "group": "Software Development",
        "description": "Belajar dari orang lain adalah cara terbaik untuk berkembang"
    },
    {
        "id": "85ea8ab9-13e9-4a73-be2b-02ae939175f1",
        "position": 179,
        "username": "reid",
        "firstName": "Reid",
        "lastName": "Nolan",
        "email": "reidnolan@example.com",
        "birthDate": "Sat Mar 04 1995",
        "basicSalary": 92381,
        "status": "Available for Hire",
        "group": "Technical Support",
        "description": "Jangan hanya bermimpi, tapi wujudkan dengan tindakan nyata"
    },
    {
        "id": "0259cddd-3f7b-4d4e-8628-575fd84f4e7f",
        "position": 180,
        "username": "jude",
        "firstName": "Jude",
        "lastName": "Spencer",
        "email": "judespencer@example.com",
        "birthDate": "Thu Apr 25 2002",
        "basicSalary": 52558,
        "status": "Intern",
        "group": "Customer Service",
        "description": "Belajar dari pengalaman adalah cara terbaik untuk berkembang"
    },
    {
        "id": "6a368f24-bab1-49f0-b9b9-192d95eb9c1e",
        "position": 181,
        "username": "quinn",
        "firstName": "Quinn",
        "lastName": "Sawyer",
        "email": "quinnsawyer@example.com",
        "birthDate": "Fri Sep 27 2002",
        "basicSalary": 107177,
        "status": "Terminated",
        "group": "UI/UX Design",
        "description": "Jangan menunda pekerjaan, karena waktu tidak bisa diulang"
    },
    {
        "id": "6f3ca580-e27d-47b7-b250-626f4c7c4bad",
        "position": 182,
        "username": "brody",
        "firstName": "Brody",
        "lastName": "Miles",
        "email": "brodymiles@example.com",
        "birthDate": "Mon Jul 03 2000",
        "basicSalary": 83885,
        "status": "Intern",
        "group": "DevOps",
        "description": "Ketekunan adalah rahasia dari banyak keberhasilan"
    },
    {
        "id": "9647e79d-5ac5-4f05-9495-e11fe43a60e6",
        "position": 183,
        "username": "santo",
        "firstName": "Santo",
        "lastName": "Jurich",
        "email": "santojurich@example.com",
        "birthDate": "Thu Oct 22 1987",
        "basicSalary": 95898,
        "status": "Sabbatical",
        "group": "Finance",
        "description": "Kreativitas tidak memiliki batas"
    },
    {
        "id": "64fff3e1-370b-45f4-aed7-6ba9266aca79",
        "position": 184,
        "username": "ridwan",
        "firstName": "Ridwan",
        "lastName": "Hutapea",
        "email": "ridwanhutapea@example.com",
        "birthDate": "Wed Jul 03 1985",
        "basicSalary": 113782,
        "status": "Retired",
        "group": "DevOps",
        "description": "Jangan hanya bermimpi, tapi wujudkan dengan tindakan nyata"
    },
    {
        "id": "a830d257-3f2a-47c4-8eaa-923f6048fe22",
        "position": 185,
        "username": "niot",
        "firstName": "Niot",
        "lastName": "Triyani",
        "email": "niottriyani@example.com",
        "birthDate": "Mon Sep 12 1988",
        "basicSalary": 99859,
        "status": "Part-Time",
        "group": "Customer Service",
        "description": "Jangan lupa istirahat dan tetap sehat"
    },
    {
        "id": "36be783b-4daa-40d1-80a7-7546bfc8fe30",
        "position": 186,
        "username": "saepul",
        "firstName": "Saepul",
        "lastName": "Abdul",
        "email": "saepulabdul@example.com",
        "birthDate": "Tue Jul 09 1996",
        "basicSalary": 33940,
        "status": "Retired",
        "group": "UI/UX Design",
        "description": "Setiap tantangan adalah kesempatan untuk tumbuh lebih kuat"
    },
    {
        "id": "cf455c0b-9a09-4a64-8639-6fd324128e67",
        "position": 187,
        "username": "andi",
        "firstName": "Andi",
        "lastName": "Saputra",
        "email": "andisaputra@example.com",
        "birthDate": "Thu Dec 17 1987",
        "basicSalary": 81935,
        "status": "Active",
        "group": "DevOps",
        "description": "Jangan biarkan kegagalan menghentikan langkahmu"
    },
    {
        "id": "ef517935-bba4-461c-aeff-01d08c5f71d3",
        "position": 188,
        "username": "budi",
        "firstName": "Budi",
        "lastName": "Santoso",
        "email": "budisantoso@example.com",
        "birthDate": "Fri Mar 25 1988",
        "basicSalary": 95843,
        "status": "Inactive",
        "group": "Public Relations",
        "description": "Berpikirlah positif, karena pikiran adalah awal dari segalanya"
    },
    {
        "id": "8215559f-33b2-468b-815b-8e3f0aff6dd0",
        "position": 189,
        "username": "chandra",
        "firstName": "Chandra",
        "lastName": "Wijaya",
        "email": "chandrawijaya@example.com",
        "birthDate": "Wed Jul 04 2001",
        "basicSalary": 88004,
        "status": "Layoff",
        "group": "Finance",
        "description": "Ketekunan adalah rahasia dari banyak keberhasilan"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c9d2",
        "position": 190,
        "username": "deni",
        "firstName": "Deni",
        "lastName": "Kurniawan",
        "email": "denikurniawan@example.com",
        "birthDate": "Sun Apr 28 1996",
        "basicSalary": 36663,
        "status": "Terminated",
        "group": "DevOps",
        "description": "Setiap tantangan adalah kesempatan untuk tumbuh lebih kuat"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c191",
        "position": 191,
        "username": "susanto91",
        "firstName": "Susanto",
        "lastName": "Abdullah",
        "email": "susantoabdullah@example.com",
        "birthDate": "Mon Jan 01 1990",
        "basicSalary": 75000,
        "status": "Active",
        "group": "Engineering",
        "description": "Kesuksesan dimulai dari langkah pertama"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c192",
        "position": 192,
        "username": "andika92",
        "firstName": "Andika",
        "lastName": "Putra",
        "email": "andikaputra@example.com",
        "birthDate": "Tue Feb 02 1991",
        "basicSalary": 82000,
        "status": "On Leave",
        "group": "Finance",
        "description": "Jangan takut gagal, terus mencoba"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c193",
        "position": 193,
        "username": "joko93",
        "firstName": "Joko",
        "lastName": "Santoso",
        "email": "jokosantoso@example.com",
        "birthDate": "Wed Mar 03 1992",
        "basicSalary": 78000,
        "status": "Remote",
        "group": "HR",
        "description": "Komunikasi yang baik adalah kunci"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c194",
        "position": 194,
        "username": "bayu94",
        "firstName": "Bayu",
        "lastName": "Wibowo",
        "email": "bayuwibowo@example.com",
        "birthDate": "Thu Apr 04 1993",
        "basicSalary": 90000,
        "status": "Suspended",
        "group": "Sales",
        "description": "Percayalah pada proses"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c195",
        "position": 195,
        "username": "rizky95",
        "firstName": "Rizky",
        "lastName": "Hidayat",
        "email": "rizkyhidayat@example.com",
        "birthDate": "Fri May 05 1994",
        "basicSalary": 95000,
        "status": "Transferred",
        "group": "Customer Service",
        "description": "Kesabaran akan membuahkan hasil"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c196",
        "position": 196,
        "username": "agus96",
        "firstName": "Agus",
        "lastName": "Saputra",
        "email": "agussaputra@example.com",
        "birthDate": "Sat Jun 06 1995",
        "basicSalary": 88000,
        "status": "Terminated",
        "group": "Technical Support",
        "description": "Bekerja dengan hati menghasilkan karya terbaik"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c197",
        "position": 197,
        "username": "dimas97",
        "firstName": "Dimas",
        "lastName": "Pratama",
        "email": "dimaspratama@example.com",
        "birthDate": "Sun Jul 07 1996",
        "basicSalary": 87000,
        "status": "Inactive",
        "group": "Software Development",
        "description": "Kejujuran adalah dasar dari segalanya"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c198",
        "position": 198,
        "username": "eko98",
        "firstName": "Eko",
        "lastName": "Surya",
        "email": "ekosurya@example.com",
        "birthDate": "Mon Aug 08 1997",
        "basicSalary": 89000,
        "status": "Maternity Leave",
        "group": "Public Relations",
        "description": "Belajarlah dari setiap kesalahan"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c199",
        "position": 199,
        "username": "farhan99",
        "firstName": "Farhan",
        "lastName": "Maulana",
        "email": "farhanmaulana@example.com",
        "birthDate": "Tue Sep 09 1998",
        "basicSalary": 91000,
        "status": "Part-Time",
        "group": "Engineering",
        "description": "Disiplin membawa kesuksesan"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c200",
        "position": 200,
        "username": "irfan00",
        "firstName": "Irfan",
        "lastName": "Ramadhan",
        "email": "irfanramadhan@example.com",
        "birthDate": "Wed Oct 10 1999",
        "basicSalary": 86000,
        "status": "Transferred",
        "group": "HR",
        "description": "Kesempatan datang bagi mereka yang siap"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c201",
        "position": 201,
        "username": "arif01",
        "firstName": "Arif",
        "lastName": "Nugroho",
        "email": "arifnugroho@example.com",
        "birthDate": "Thu Nov 11 2000",
        "basicSalary": 84000,
        "status": "Available for Hire",
        "group": "Sales",
        "description": "Jangan pernah berhenti belajar"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c202",
        "position": 202,
        "username": "yusuf02",
        "firstName": "Yusuf",
        "lastName": "Fauzi",
        "email": "yusuffauzi@example.com",
        "birthDate": "Fri Dec 12 2001",
        "basicSalary": 92000,
        "status": "Inactive",
        "group": "Technical Support",
        "description": "Bersyukur adalah kunci kebahagiaan"
    },
    {
        "id": "ff4807ed-f3dd-4e51-ba7f-876f0666c203",
        "position": 203,
        "username": "reza03",
        "firstName": "Reza",
        "lastName": "Wijaya",
        "email": "rezawijaya@example.com",
        "birthDate": "Sat Jan 13 2002",
        "basicSalary": 93000,
        "status": "Active",
        "group": "Software Development",
        "description": "Semangat pantang menyerah!"
    }
]as unknown as Employee[]